services:
  db:
    image: mysql:8.0
    container_name: clinica_db
    environment:
      MYSQL_DATABASE: clinica
      MYSQL_USER: clinica
      MYSQL_PASSWORD: clinica
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30

  php:
    build:
      context: ./clinica-backend
      dockerfile: Dockerfile
      target: php
    image: clinicadieteticamv-php
    container_name: clinica_php
    working_dir: /var/www
    volumes:
      - ./clinica-backend:/var/www 
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: clinica
      DB_USERNAME: clinica
      DB_PASSWORD: clinica
      APP_ENV: local
      APP_URL: http://localhost:8081
      SEED_ON_START: "true" # Cambiar a "true" si quieres que se ejecuten los seeders al iniciar
    depends_on:
      db:
        condition: service_healthy

  api-nginx:
    image: nginx:1.25-alpine
    container_name: clinica_api
    depends_on:
      - php
    ports:
      - "8081:80" # API en http://localhost:8081, Acordarse de cambiarla en las variables de entorno de Laravel y Angular
    volumes:
      - ./clinica-backend:/var/www:ro
      - ./clinica-backend/.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    
    

  frontend:
    build:
      context: ./clinica-frontend
      dockerfile: Dockerfile
      args:
        NG_CONFIGURATION: development
        BASE_HREF: "/"
    ports:
      - "8080:80"
    depends_on:
      - api-nginx

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: clinica_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
    depends_on:
      - db
    ports:
      - "127.0.0.1:8082:80"

volumes:
  db_data:
