version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: clinica_db
    environment:
      MYSQL_DATABASE: clinica
      MYSQL_USER: clinica
      MYSQL_PASSWORD: clinica
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    build:
      context: ./clinica-backend
      dockerfile: Dockerfile
    container_name: clinica_php
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: clinica
      DB_USERNAME: clinica
      DB_PASSWORD: clinica
      APP_ENV: production
      APP_KEY: base64:xxxxx
      APP_URL: http://localhost:8081
    depends_on:
      - db

  api-nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./clinica-backend/.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./clinica-backend/public:/var/www/public:ro
    container_name: clinica_api
    depends_on:
      - php
    ports:
      - "8081:80" # API en http://localhost:8081, Acordarse de cambiarla en las variables de entorno de Laravel y Angular

  frontend:
    build:
      context: ./clinica-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api-nginx

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: clinica_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
    depends_on:
      - db
    ports:
      - "127.0.0.1:8082:80"

volumes:
  db_data:
