#Como en local no tengo Traefik, uso este override para no tener errores de arranque
services:
  api:
    ports:
      - "8081:80"
    volumes:
      - ./clinica-backend/.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    ports:
      - "8080:80"