networks:
  edge:
    external: true

volumes:
  db_data: {}
  laravel_storage: {}

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: clinica
      MYSQL_USER: clinica
      MYSQL_PASSWORD: clinica
      MYSQL_ROOT_PASSWORD: root
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [edge]

  php:
    image: ghcr.io/sebasrodmag/clinicamv-backend:php-main
    env_file: [ ./secrets/clinica.env ]
    environment:
      MIGRATE_ON_START: "true" # Cambiar a "true" si quieres que se ejecuten los seeders al iniciar el deploy
      SEED_ON_START: "true"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    # Persiste subidas/logs/etc. de Laravel
    volumes:
      - laravel_storage:/var/www/storage
    networks: [edge]

  api:
    image: ghcr.io/sebasrodmag/clinicamv-backend:api-main
    restart: unless-stopped
    depends_on: [php]
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.clinicamv.lol`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=lets
      - traefik.http.services.api.loadbalancer.server.port=80
    networks: [edge]

  frontend:
    image: ghcr.io/sebasrodmag/clinicamv-frontend:main
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.front.rule=Host(`app.clinicamv.lol`)
      - traefik.http.routers.front.entrypoints=websecure
      - traefik.http.routers.front.tls.certresolver=lets
      - traefik.http.services.front.loadbalancer.server.port=80
    networks: [edge]

  # Opcional: solo accesible desde localhost del servidor
  phpmyadmin:
    image: phpmyadmin:5.2
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
    depends_on: [db]
    ports:
      - "127.0.0.1:8082:80"
    networks: [edge]
