#Como en local no tengo Traefik, uso este override para no tener errores de arranque solo en local
services:
  db:
    ports:
      - "3306:3306"
    networks: [default]

  php:
    environment:
      APP_ENV: local
      APP_URL: http://localhost:8081
      CORS_ALLOWED_ORIGINS: http://localhost:8080
      SESSION_DRIVER: file
      MIGRATE_ON_START: "true"
      SEED_ON_START: "true"
    networks: [default]

  api:
    ports:
      - "8081:80"
    volumes:
      - ./clinica-backend/.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels: []
    networks: [default]

  frontend:
    build:
      context: ./clinica-frontend
      dockerfile: Dockerfile
      args:
        NG_CONFIGURATION: development   # debe llamar al environment.ts
        BASE_HREF: "/"                 # o "/clinicamv/" tengo que verificar que coincida con la ruta base en Angular
    image: clinicamv-frontend:dev
    ports:
      - "8080:80"
    labels: []
    networks: [default]

  phpmyadmin:
    ports:
      - "127.0.0.1:8082:80"
    networks: [default]
