name: Build & Push clinicamv-frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "clinica-frontend/**"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: clinica-frontend
          file: clinica-frontend/Dockerfile
          push: true
          build-args: |
            BASE_HREF=/clinicamv/
          tags: ghcr.io/sebasrodmag/clinicamv-frontend:main
