name: Build & Push clinicamv-php

on:
  push:
    branches: [ "main" ]
    paths:
      - "clinica-backend/**"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: clinica-backend
          file: clinica-backend/Dockerfile
          push: true
          tags: ghcr.io/sebasrodmag/clinicamv-php:main
