name: Build & Push clinicamv-frontend

on:
  push:
    branches: [ "main" ]
    paths: [ "clinica-frontend/**" ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        shell: bash

      - uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: clinica-frontend
          file: clinica-frontend/Dockerfile
          push: true
          build-args: |
            BASE_HREF=/
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/clinicamv-frontend:main
            ghcr.io/${{ env.OWNER_LC }}/clinicamv-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
