name: Build & Push clinicamv-frontend

on:
  push:
    branches: [ "main" ]
    paths: [ "clinica-frontend/**" ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        with:
          install: true

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: clinica-frontend
          file: clinica-frontend/Dockerfile
          push: true
          build-args: |
            BASE_HREF=/
          tags: |
            ghcr.io/${{ github.repository_owner }}/clinicamv-frontend:main
            ghcr.io/${{ github.repository_owner }}/clinicamv-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
